# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/landmarktoolboxbase.ui'
#
# Created: Mon Mar  9 18:56:53 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(378, 606)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spnLandmarkClass = QgsSpinBox(self.dockWidgetContents)
        self.spnLandmarkClass.setObjectName(_fromUtf8("spnLandmarkClass"))
        self.horizontalLayout_2.addWidget(self.spnLandmarkClass)
        self.btnUpdateLandmark = QtGui.QPushButton(self.dockWidgetContents)
        self.btnUpdateLandmark.setObjectName(_fromUtf8("btnUpdateLandmark"))
        self.horizontalLayout_2.addWidget(self.btnUpdateLandmark)
        self.btnDeleteLandmark = QtGui.QPushButton(self.dockWidgetContents)
        self.btnDeleteLandmark.setObjectName(_fromUtf8("btnDeleteLandmark"))
        self.horizontalLayout_2.addWidget(self.btnDeleteLandmark)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 2)
        self.btnAddPhoto = QtGui.QToolButton(self.dockWidgetContents)
        self.btnAddPhoto.setAutoRaise(True)
        self.btnAddPhoto.setObjectName(_fromUtf8("btnAddPhoto"))
        self.gridLayout_2.addWidget(self.btnAddPhoto, 4, 2, 1, 1)
        self.splitter = QtGui.QSplitter(self.dockWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.lstPhotos = QtGui.QListView(self.splitter)
        self.lstPhotos.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.lstPhotos.setIconSize(QtCore.QSize(75, 50))
        self.lstPhotos.setGridSize(QtCore.QSize(75, 80))
        self.lstPhotos.setViewMode(QtGui.QListView.IconMode)
        self.lstPhotos.setObjectName(_fromUtf8("lstPhotos"))
        self.grpAttributes = QgsCollapsibleGroupBox(self.splitter)
        self.grpAttributes.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.grpAttributes.setObjectName(_fromUtf8("grpAttributes"))
        self.gridLayout = QtGui.QGridLayout(self.grpAttributes)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtPhotoComment = TextEdit(self.grpAttributes)
        self.txtPhotoComment.setObjectName(_fromUtf8("txtPhotoComment"))
        self.gridLayout.addWidget(self.txtPhotoComment, 1, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.grpAttributes)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 13, 1, 1, 1)
        self.btnUpdatePhoto = QtGui.QPushButton(self.grpAttributes)
        self.btnUpdatePhoto.setObjectName(_fromUtf8("btnUpdatePhoto"))
        self.gridLayout.addWidget(self.btnUpdatePhoto, 15, 0, 1, 1)
        self.btnDeletePhoto = QtGui.QPushButton(self.grpAttributes)
        self.btnDeletePhoto.setObjectName(_fromUtf8("btnDeletePhoto"))
        self.gridLayout.addWidget(self.btnDeletePhoto, 15, 1, 1, 1)
        self.chkRemovePhoto = QtGui.QCheckBox(self.dockWidgetContents)
        self.chkRemovePhoto.setObjectName(_fromUtf8("chkRemovePhoto"))
        self.gridLayout.addWidget(self.chkRemovePhoto, 16, 1, 1, 1)
        self.edPhotoDate = QgsDateTimeEdit(self.grpAttributes)
        self.edPhotoDate.setCalendarPopup(True)
        self.edPhotoDate.setObjectName(_fromUtf8("edPhotoDate"))
        self.gridLayout.addWidget(self.edPhotoDate, 14, 1, 1, 1)
        self.spnPhotoAngle = QgsSpinBox(self.grpAttributes)
        self.spnPhotoAngle.setMaximum(360)
        self.spnPhotoAngle.setObjectName(_fromUtf8("spnPhotoAngle"))
        self.gridLayout.addWidget(self.spnPhotoAngle, 14, 0, 1, 1)
        self.lePhotoTitle = QtGui.QLineEdit(self.grpAttributes)
        self.lePhotoTitle.setObjectName(_fromUtf8("lePhotoTitle"))
        self.gridLayout.addWidget(self.lePhotoTitle, 0, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.grpAttributes)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 13, 0, 1, 1)
        self.leRegistrant = QtGui.QLineEdit(self.grpAttributes)
        self.leRegistrant.setObjectName(_fromUtf8("leRegistrant"))
        self.gridLayout.addWidget(self.leRegistrant, 6, 0, 1, 2)
        self.lerRference = QtGui.QLineEdit(self.grpAttributes)
        self.lerRference.setObjectName(_fromUtf8("lerRference"))
        self.gridLayout.addWidget(self.lerRference, 11, 0, 1, 2)
        self.leComment = QtGui.QLineEdit(self.grpAttributes)
        self.leComment.setObjectName(_fromUtf8("leComment"))
        self.gridLayout.addWidget(self.leComment, 10, 0, 1, 2)
        self.leKeywords = QtGui.QLineEdit(self.grpAttributes)
        self.leKeywords.setObjectName(_fromUtf8("leKeywords"))
        self.gridLayout.addWidget(self.leKeywords, 2, 0, 1, 2)
        self.leKeyword1 = QtGui.QLineEdit(self.grpAttributes)
        self.leKeyword1.setObjectName(_fromUtf8("leKeyword1"))
        self.gridLayout.addWidget(self.leKeyword1, 3, 0, 1, 2)
        self.leKeyword2 = QtGui.QLineEdit(self.grpAttributes)
        self.leKeyword2.setObjectName(_fromUtf8("leKeyword2"))
        self.gridLayout.addWidget(self.leKeyword2, 4, 0, 1, 2)
        self.leKeyword3 = QtGui.QLineEdit(self.grpAttributes)
        self.leKeyword3.setObjectName(_fromUtf8("leKeyword3"))
        self.gridLayout.addWidget(self.leKeyword3, 5, 0, 1, 2)
        self.gridLayout_2.addWidget(self.splitter, 6, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 3)
        self.leLandmarkTitle = QtGui.QLineEdit(self.dockWidgetContents)
        self.leLandmarkTitle.setObjectName(_fromUtf8("leLandmarkTitle"))
        self.gridLayout_2.addWidget(self.leLandmarkTitle, 2, 0, 1, 3)
        self.cmbLayers = QgsMapLayerComboBox(self.dockWidgetContents)
        self.cmbLayers.setObjectName(_fromUtf8("cmbLayers"))
        self.gridLayout_2.addWidget(self.cmbLayers, 0, 1, 1, 2)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.cmbLayers, self.leLandmarkTitle)
        DockWidget.setTabOrder(self.leLandmarkTitle, self.spnLandmarkClass)
        DockWidget.setTabOrder(self.spnLandmarkClass, self.btnUpdateLandmark)
        DockWidget.setTabOrder(self.btnUpdateLandmark, self.btnDeleteLandmark)
        DockWidget.setTabOrder(self.btnDeleteLandmark, self.btnAddPhoto)
        DockWidget.setTabOrder(self.btnAddPhoto, self.lstPhotos)
        DockWidget.setTabOrder(self.lstPhotos, self.lePhotoTitle)
        DockWidget.setTabOrder(self.lePhotoTitle, self.txtPhotoComment)
        DockWidget.setTabOrder(self.txtPhotoComment, self.leKeyword2)
        DockWidget.setTabOrder(self.leKeywords, self.leKeyword1)
        DockWidget.setTabOrder(self.leKeyword1, self.leKeyword2)
        DockWidget.setTabOrder(self.leKeyword2, self.leKeyword3)
        DockWidget.setTabOrder(self.leKeyword3, self.leRegistrant)
        DockWidget.setTabOrder(self.leRegistrant, self.leComment)
        DockWidget.setTabOrder(self.leComment, self.lerRference)
        DockWidget.setTabOrder(self.lerRference, self.spnPhotoAngle)
        DockWidget.setTabOrder(self.spnPhotoAngle, self.edPhotoDate)
        DockWidget.setTabOrder(self.edPhotoDate, self.btnUpdatePhoto)
        DockWidget.setTabOrder(self.btnUpdatePhoto, self.btnDeletePhoto)
        DockWidget.setTabOrder(self.btnDeletePhoto,self.chkRemovePhoto)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "Landmark Photo Overlay", None))
        self.label.setText(_translate("DockWidget", "Landmark layer", None))
        self.label_5.setText(_translate("DockWidget", "Classification", None))
        self.btnUpdateLandmark.setText(_translate("DockWidget", "Save", None))
        self.btnDeleteLandmark.setText(_translate("DockWidget", "Delete", None))
        self.label_6.setText(_translate("DockWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Landmark photos</span></p></body></html>", None))
        self.btnAddPhoto.setToolTip(_translate("DockWidget", "Add photo to landmark", None))
        self.btnAddPhoto.setText(_translate("DockWidget", "...", None))
        self.label_4.setText(_translate("DockWidget", "Date", None))
        self.btnUpdatePhoto.setText(_translate("DockWidget", "Save", None))
        self.btnDeletePhoto.setText(_translate("DockWidget", "Delete", None))
        self.chkRemovePhoto.setText(_translate("DockWidget", "Remove Photo File", None))
        self.lePhotoTitle.setPlaceholderText(_translate("DockWidget", "film_no", None))
        self.edPhotoDate.setDisplayFormat(_translate("DockWidget", "dd.MM.yy", None))
        self.lePhotoTitle.setPlaceholderText(_translate("DockWidget", "Title", None))
        self.label_3.setText(_translate("DockWidget", "Angle", None))
        self.leRegistrant.setPlaceholderText(_translate("DockWidget", "registrant", None))
        self.lerRference.setPlaceholderText(_translate("DockWidget", "reference", None))
        self.leComment.setPlaceholderText(_translate("DockWidget", "Comment", None))
        self.leKeywords.setPlaceholderText(_translate("DockWidget", "Keywords", None))
        self.leKeyword1.setPlaceholderText(_translate("DockWidget", "Keyword1", None))
        self.leKeyword2.setPlaceholderText(_translate("DockWidget", "Keyword2", None))
        self.leKeyword3.setPlaceholderText(_translate("DockWidget", "Keyword3", None))
        self.label_2.setText(_translate("DockWidget", "<html><head/><body><p><span style=\" font-weight:600;\">Landmark properties</span></p></body></html>", None))
        self.leLandmarkTitle.setPlaceholderText(_translate("DockWidget", "Title", None))
        self.txtPhotoComment.setPlaceholderText(_translate("DockWidget", "Description", None))


from qgis.gui import QgsSpinBox, QgsCollapsibleGroupBox, QgsMapLayerComboBox, QgsDateTimeEdit
from GkukanMusiumdb.gui.textedit import TextEdit
